// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzhockwtdrlafnbemfxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aG9ja3d0ZHJsYWZuYmVtZnhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDE5MzMsImV4cCI6MjA2MDIxNzkzM30.E-GOheO2NTY0HWnHV4O8l4KT_oQMIOTit5aiuyTGCP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);